version: '2'

services:
  django:
    build:
      context: .
      dockerfile: compose/django/Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    #command: /app/compose/django/start-dev.sh
    networks:
      vpcbr:
        ipv4_address: 10.5.0.8

  ansible:
    build:
      context: .
      dockerfile: compose/ansible/Dockerfile
    volumes:
      - .:/app
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
